##############################################################
### Kitty settings configfile (~/.config/kitty/kitty.conf) ###
##############################################################

# load mecha
include ~/.cache/wal/colors-kitty.conf
##include ~/.config/kitty/theme/macchiato.conf


# Windows transparency settingsssss
background_opacity 0.58

background_image_path none
background_image_linear no

scrollback_indicator_opacity 0

url_color         #0087bd
url_style         dotted


# Font settings
font_family       FiraCode Nerd Font
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         13

#adjust_line_height 120%
modify_font baseline 0
modify_font line_height 2pt
confirm_os_window_close 0

mouse_hide_wait   6.0
cursor_shape      block

enable_cursor_trail yes
cursor_trail 8
cursor_animation_duration 0.5
