#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/


# --- GPU & Backend (Aquamarine) ---
env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
env = AQ_NO_ATOMIC,0

# --- Graphics & Performance (Mesa/RADV) ---
env = RADV_PERFTEST,ext_sync
env = RADV_DEBUG,syncshaders
env = LIBVA_DRIVER_NAME,radeonsi
env = VDPAU_DRIVER,radeonsi
env = ANGLE_DEFAULT_PLATFORM,vulkan

# --- Toolkit Backends (Wayland Native) ---
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# --- XDG Specifications ---
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# --- Display & UI Scaling ---
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = GDK_SCALE,auto
env = XWAYLAND_NO_GLAMOR,0

# --- Cursor (Hyprcursor) ---
env = HYPRCURSOR_THEME,"Hakurei Reimu-hyprcursor"
env = HYPRCURSOR_SIZE,24
#env = XCURSOR_THEME,"Hakurei Reimu-hyprcursor"
#env = XCURSOR_SIZE,24

# --- IME (Fcitx5) ---
env = XMODIFIERS,@im=fcitx

# --- PATH ---
